# Generated by Django 4.2.4 on 2023-08-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
        ),
    ]
