# Generated by Django 4.2.4 on 2023-08-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_hotel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
    ]
